### ISSUE TITLE
model_data/X_train.csv

### ISSUE THREAD

**Issue by RooKichenn** [Madao-1639/auto-pricing#1]
您好，关于model_test文件中的X_train.csv是怎么生成的呢，如果方便的话可以可以上传一下代码吗

**Comment by Madao-1639** [comment]
> 

我在 XGBR.py 中，模型训练之前，设了一个断点把训练集和测试集数据手动导出到 model_test 中（如果你已经从用爬虫获取了数据并在 process.ipynb 做了预处理，这部分数据我没有上传），只是为了在 model_test.ipynb 中测试模型的性能。

**Comment by RooKichenn** [comment]
是的，我在XGBR.py中看到划分数据集的代码了，也就是说如果我想对训练好的模型进行测试，只需要将划分好的X_train、X_test等传入模型就可以了是吗，感谢您的回复为我解答了疑惑！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Madao-1639/auto-pricing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月30日(星期一) 中午12:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Madao-1639/auto-pricing] model_data/X_train.csv (Issue #1)





   
我在 XGBR.py 中，模型训练之前，设了一个断点把训练集和测试集数据手动导出到 model_test 中（如果你已经从用爬虫获取了数据并在 process.ipynb 做了预处理，这部分数据我没有上传），只是为了在 model_test.ipynb 中测试模型的性能。

**Comment by Madao-1639** [comment]
> 

是的
